export default [
  {
    name: 'Luke Skywalker',
    imageUrl: 'http://facetheforce.today/luke',
    gender: 'male',
    birthYear: '3523',
    eyeColor: 'blue',
  },
  {
    name: 'C-3PO',
    imageUrl: 'http://facetheforce.today/c3po',
    gender: 'male',
    birthYear: '3523',
    eyeColor: 'blue',
  },
  {
    name: 'R2-D2',
    imageUrl: 'http://facetheforce.today/r2d2',
    gender: 'male',
    birthYear: '3523',
    eyeColor: 'blue',
  },
  {
    name: 'Darth Vader',
    imageUrl: 'http://facetheforce.today/darthvader',
    gender: 'male',
    birthYear: '3523',
    eyeColor: 'blue',
  },
  {
    name: 'Leia Organa',
    imageUrl: 'http://facetheforce.today/leia',
    gender: 'male',
    birthYear: '3523',
    eyeColor: 'blue',
  },
  {
    name: 'Obi-Wan Kenobi',
    imageUrl: 'http://facetheforce.today/obiwan',
    gender: 'male',
    birthYear: '3523',
    eyeColor: 'blue',
  },
  {
    name: 'Anakin Skywalker',
    imageUrl: 'http://facetheforce.today/anakin',
    gender: 'male',
    birthYear: '3523',
    eyeColor: 'blue',
  },
];
