export default {
  loadingData: false,
  characterCount: 87,
  nextEndpoint: 'https://swapi.co/api/people/?page=2&search=',
  previousEndpoint: null,
  searchArray: [
    {
      name: 'Luke Skywalker',
      height: '172',
      mass: '77',
      gender: 'male',
      hairColor: 'blond',
      skinColor: 'fair',
      eyeColor: 'blue',
      birthYear: '19BBY',
    },
    {
      name: 'C-3PO',
      height: '167',
      mass: '75',
      gender: 'n/a',
      hairColor: 'n/a',
      skinColor: 'gold',
      eyeColor: 'yellow',
      birthYear: '112BBY',
    },
    {
      name: 'R2-D2',
      height: '96',
      mass: '32',
      gender: 'n/a',
      hairColor: 'n/a',
      skinColor: 'white, blue',
      eyeColor: 'red',
      birthYear: '33BBY',
    },
    {
      name: 'Darth Vader',
      height: '202',
      mass: '136',
      gender: 'male',
      hairColor: 'none',
      skinColor: 'white',
      eyeColor: 'yellow',
      birthYear: '41.9BBY',
    },
    {
      name: 'Leia Organa',
      height: '150',
      mass: '49',
      gender: 'female',
      hairColor: 'brown',
      skinColor: 'light',
      eyeColor: 'brown',
      birthYear: '19BBY',
    },
    {
      name: 'Owen Lars',
      height: '178',
      mass: '120',
      gender: 'male',
      hairColor: 'brown, grey',
      skinColor: 'light',
      eyeColor: 'blue',
      birthYear: '52BBY',
    },
    {
      name: 'Beru Whitesun lars',
      height: '165',
      mass: '75',
      gender: 'female',
      hairColor: 'brown',
      skinColor: 'light',
      eyeColor: 'blue',
      birthYear: '47BBY',
    },
    {
      name: 'R5-D4',
      height: '97',
      mass: '32',
      gender: 'n/a',
      hairColor: 'n/a',
      skinColor: 'white, red',
      eyeColor: 'red',
      birthYear: 'unknown',
    },
    {
      name: 'Biggs Darklighter',
      height: '183',
      mass: '84',
      gender: 'male',
      hairColor: 'black',
      skinColor: 'light',
      eyeColor: 'brown',
      birthYear: '24BBY',
    },
    {
      name: 'Obi-Wan Kenobi',
      height: '182',
      mass: '77',
      gender: 'male',
      hairColor: 'auburn, white',
      skinColor: 'fair',
      eyeColor: 'blue-gray',
      birthYear: '57BBY',
    },
  ],
  savedFilter: 'All',
  savedArray: [
    {
      name: 'Luke Skywalker',
      height: '172',
      mass: '77',
      gender: 'male',
      hairColor: 'blond',
      skinColor: 'fair',
      eyeColor: 'blue',
      birthYear: '19BBY',
    },
    {
      name: 'Leia Organa',
      height: '150',
      mass: '49',
      gender: 'female',
      hairColor: 'brown',
      skinColor: 'light',
      eyeColor: 'brown',
      birthYear: '19BBY',
    },
    {
      name: 'R2-D2',
      height: '96',
      mass: '32',
      gender: 'n/a',
      hairColor: 'n/a',
      skinColor: 'white, blue',
      eyeColor: 'red',
      birthYear: '33BBY',
    },
  ],
  characterSelected: {
    name: 'R2-D2',
    height: '96',
    mass: '32',
    gender: 'n/a',
    hairColor: 'n/a',
    skinColor: 'white, blue',
    eyeColor: 'red',
    birthYear: '33BBY',
  },
  searchText: '',
  error: '',
};
