export default [
  {
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hairColor: 'blond',
    skinColor: 'fair',
    eyeColor: 'blue',
    birthYear: '19BBY',
    gender: 'male',
  },
  {
    name: 'C-3PO',
    height: '167',
    mass: '75',
    hairColor: 'n/a',
    skinColor: 'gold',
    eyeColor: 'yellow',
    birthYear: '112BBY',
    gender: 'n/a',
  },
  {
    name: 'R2-D2',
    height: '96',
    mass: '32',
    hairColor: 'n/a',
    skinColor: 'white, blue',
    eyeColor: 'red',
    birthYear: '33BBY',
    gender: 'n/a',
  },
  {
    name: 'Darth Vader',
    height: '202',
    mass: '136',
    hairColor: 'none',
    skinColor: 'white',
    eyeColor: 'yellow',
    birthYear: '41.9BBY',
    gender: 'male',
  },
  {
    name: 'Leia Organa',
    height: '150',
    mass: '49',
    hairColor: 'brown',
    skinColor: 'light',
    eyeColor: 'brown',
    birthYear: '19BBY',
    gender: 'female',
  },
  {
    name: 'Owen Lars',
    height: '178',
    mass: '120',
    hairColor: 'brown, grey',
    skinColor: 'light',
    eyeColor: 'blue',
    birthYear: '52BBY',
    gender: 'male',
  },
  {
    name: 'Beru Whitesun lars',
    height: '165',
    mass: '75',
    hairColor: 'brown',
    skinColor: 'light',
    eyeColor: 'blue',
    birthYear: '47BBY',
    gender: 'female',
  },
  {
    name: 'R5-D4',
    height: '97',
    mass: '32',
    hairColor: 'n/a',
    skinColor: 'white, red',
    eyeColor: 'red',
    birthYear: 'unknown',
    gender: 'n/a',
  },
  {
    name: 'Biggs Darklighter',
    height: '183',
    mass: '84',
    hairColor: 'black',
    skinColor: 'light',
    eyeColor: 'brown',
    birthYear: '24BBY',
    gender: 'male',
  },
  {
    name: 'Obi-Wan Kenobi',
    height: '182',
    mass: '77',
    hairColor: 'auburn, white',
    skinColor: 'fair',
    eyeColor: 'blue-gray',
    birthYear: '57BBY',
    gender: 'male',
  },
];
