export default {
  TOGGLE_DATA_LOADING: 'TOGGLE_DATA_LOADING',
  FETCH_API_START: 'FETCH_API_START',
  FETCH_API_SUCCESS: 'FETCH_API_SUCCESS',
  FETCH_API_FAILURE: 'FETCH_API_FAILURE',
  SAVE_CHARACTER: 'SAVE_CHARACTER',
  REMOVE_CHARACTER: 'REMOVE_CHARACTER',
  SELECT_CHARACTER: 'SELECT_CHARACTER',
  SET_FILTER: 'SET_FILTER',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
};
